name: Build and Push Built Files

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Bun install
        run: bun install

      - name: Clean generated JS files
        run: bun run clean

      - name: Format code
        run: bun run format

      - name: Typecheck code
        run: bun run typecheck

      - name: Build code
        run: bun run build

      - name: Commit built files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto build: Updated built JS files"
